# Generated by Django 5.2.7 on 2025-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=12)),
                ('user_email', models.CharField(max_length=50)),
                ('user_complains', models.IntegerField()),
            ],
        ),
    ]
