# Generated by Django 5.2.7 on 2025-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=20)),
                ('worker_pass', models.CharField(max_length=30)),
                ('worker_phone', models.CharField(max_length=12)),
                ('worker_email', models.CharField(max_length=50)),
            ],
        ),
    ]
