# Generated by Django 5.2.7 on 2025-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=20)),
            ],
        ),
    ]
