# Generated by Django 5.2.7 on 2025-10-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='imgname',
            field=models.CharField(default='idc', max_length=50),
        ),
        migrations.AddField(
            model_name='complain',
            name='info',
            field=models.CharField(default='idc', max_length=500),
        ),
        migrations.AddField(
            model_name='complain',
            name='location',
            field=models.CharField(default='idc', max_length=50),
        ),
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(default='w', max_length=12),
        ),
        migrations.AddField(
            model_name='complain',
            name='user_name',
            field=models.CharField(default='idc', max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='domain_name',
            field=models.CharField(default='idc', max_length=20),
        ),
    ]
