# Generated by Django 5.2.7 on 2025-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_complain_imgname_complain_info_complain_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='image',
            field=models.ImageField(default='', upload_to='Main/images'),
        ),
    ]
