# Generated by Django 5.2.7 on 2025-10-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_complain_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='location',
            new_name='landmark',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='imgname',
        ),
        migrations.AddField(
            model_name='complain',
            name='locx',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='complain',
            name='locy',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
    ]
