# Generated by Django 5.2.7 on 2025-10-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_rename_location_complain_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='datee',
            field=models.CharField(default='1/1/2000', max_length=10),
        ),
    ]
