# Generated by Django 5.2.7 on 2025-10-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_complain_datee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usr',
        ),
    ]
