# Generated by Django 5.2.7 on 2025-10-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_user_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='real_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
