# Generated by Django 5.2.7 on 2025-10-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_usr_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='domain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
